import {
  type EmitContext,
  emitFile,
  type Program,
} from "@typespec/compiler";
import {
  collectServices,
  type RpcInfo,
  type ServiceInfo,
} from "@speconn/typespec-emitter-core";

export type EmitterOptions = {
  "emitter-output-dir": string;
};

async function emitKotlin(program: Program, services: ServiceInfo[], outputDir: string): Promise<void> {
  const promises: Promise<void>[] = [];

  for (const svc of services) {
    if (svc.rpcs.length === 0) continue;
    const pkg = (svc.namespace.name || "alltypes").toLowerCase().replace(/[^a-z0-9]/g, "");
    const reqType = (rpc: RpcInfo) => rpc.inputType?.name ?? "Unit";
    const resType = (rpc: RpcInfo) => rpc.outputType?.name ?? "Unit";
    const reqCodec = (rpc: RpcInfo) => rpc.inputType ? `${rpc.inputType.name}Codec` : "emptyCodec";
    const resCodec = (rpc: RpcInfo) => rpc.outputType ? `${rpc.outputType.name}Codec` : "emptyCodec";
    const allTypeNames = [...new Set(svc.rpcs.flatMap(rpc =>
      [rpc.inputType?.name, rpc.outputType?.name].filter(Boolean) as string[]
    ))];
    const allCodecNames = [...new Set(svc.rpcs.flatMap(rpc =>
      [
        rpc.inputType ? `${rpc.inputType.name}Codec` : null,
        rpc.outputType ? `${rpc.outputType.name}Codec` : null,
      ].filter(Boolean) as string[]
    ))];

    // ---- client ----
    const client: string[] = [];
    client.push("// Generated by @speconn/typespec-emitter-kotlin. DO NOT EDIT.\n");
    client.push(`package ${pkg}\n`);
    client.push("import speconn.SpeconnClient");
    client.push("import speconn.SpeconnChannel");
    client.push("import speconn.CallOptions");
    client.push("import speconn.Response");
    client.push("import speconn.StreamResponse");
    if (allTypeNames.length > 0) {
      client.push(`import ${pkg}.types.${allTypeNames.join(`\nimport ${pkg}.types.`)}`);
    }
    if (allCodecNames.length > 0) {
      client.push(`import ${pkg}.types.${allCodecNames.join(`\nimport ${pkg}.types.`)}`);
    }
    client.push('');
    client.push(`class ${svc.serviceName}Client(baseUrl: String, transport: SpeconnChannel) {`);
    for (const rpc of svc.rpcs) {
      client.push(`    private val _${rpc.name} = SpeconnClient(baseUrl, "${rpc.path}", transport)`);
    }
    for (const rpc of svc.rpcs) {
      if (rpc.isStream) {
        client.push(`    suspend fun ${rpc.name}(req: ${reqType(rpc)}, headers: Map<String, String> = emptyMap(), timeoutMs: Long? = null): StreamResponse<${resType(rpc)}> =`);
        client.push(`        _${rpc.name}.stream(${reqCodec(rpc)}, req, ${resCodec(rpc)}, CallOptions(headers, timeoutMs))`);
      } else {
        client.push(`    suspend fun ${rpc.name}(req: ${reqType(rpc)}, headers: Map<String, String> = emptyMap(), timeoutMs: Long? = null): Response<${resType(rpc)}> =`);
        client.push(`        _${rpc.name}.call(${reqCodec(rpc)}, req, ${resCodec(rpc)}, CallOptions(headers, timeoutMs))`);
      }
    }
    client.push('}\n');

    promises.push(emitFile(program, { path: `${outputDir}/${svc.serviceName}Client.kt`, content: client.join("\n") }));
  }
  await Promise.all(promises);
}

export async function $onEmit(context: EmitContext<EmitterOptions>) {
  const services = collectServices(context.program);
  await emitKotlin(context.program, services, context.emitterOutputDir);
}
